name: measure

on:
  push:
    branches: main

jobs:
  bash:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: bash -version
    - run: ./run bash bash

  c:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: cc --version
    - run: ./run c c

  deno:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: deno --version
    - run: ./run deno deno

  go:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: go version
    - run: ./run go go

  java:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: java -version
    - run: ./run java java

  node:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: node --version
    - run: ./run node node

  python:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: python --version
    - run: ./run python python

  rust:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: rustc --version
    - run: ./run rust rust
